# configuration for https://ohi-science.nceas.ucsb.edu/blz_app
study_area:       Belize
git_owner:        OHI-Science
git_repo:         blz
git_slug:         OHI-Science/blz
git_url:          https://github.com/OHI-Science/blz
app_url:          https://ohi-science.nceas.ucsb.edu/blz_app
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-03-20
ohicore_app:
  git_owner: jules32
  git_repo: blz
  git_branch: draft
  git_commit: moving App to NCEAS server

tabs_hide:        
- Calculate
- Report

